### ISSUE TITLE
Compatibility with v2.5.x

### ISSUE THREAD

**Issue by abraunegg** [bpozdena/OneDriveGUI#114] opened 2023-08-08 11:05 UTC
@bpozdena 
FYI within the next couple of weeks v2.5.0-alpha-0 will drop, and there are functionality differences (breaking changes) to how the client operates.

It would be worth keeping an eye on https://github.com/abraunegg/onedrive/discussions/2415 to track development progress, so that when the initial alpha code drops, you can start testing this against the GUI for compatibility.

**Comment by abraunegg** [comment] 2023-08-27 00:46
@bpozdena 
FYI - v2.5.0-alpha-0 has dropped: https://github.com/abraunegg/onedrive/discussions/2478

**Comment by abraunegg** [comment] 2023-09-22 07:47
FYI - v2.5.0-alpha1 has dropped: https://github.com/abraunegg/onedrive/discussions/2486

**Comment by bpozdena** [comment] 2023-10-18 19:15
If anyone is interested in testing, there is a new branch of the GUI https://github.com/bpozdena/OneDriveGUI/tree/v1.1.0-alpha0 . 

It is only compatible with the Onedrive client v2.5.0_alphaX. The path of client binary  must be manually specified in the GUI settings.

Example:
![image](https://github.com/bpozdena/OneDriveGUI/assets/24818591/9595886f-850a-4f6a-a1b4-e0bd872eb5cc)

**Comment by abraunegg** [comment] 2023-10-18 19:52
FYI 'alpha-2' is code complete, 'alpha-3' is in development, webhooks has been added back in, but not yet tested.

onedrive client version v2.5.0-alpha-3 -> #2520 .. a general announcement will be done once testing and uplift of webhooks is complete.

**Comment by abraunegg** [comment] 2024-01-09 02:27
@bpozdena 
FYI 'alpha-5' is now available: https://github.com/abraunegg/onedrive/discussions/2585

This will go through my 90+ Use Case Tests per account type to shake out any issues / bugs, then will potentially push the result out as 'beta-1'

**Comment by abraunegg** [comment] 2024-03-15 03:56
@bpozdena 
FYI , v2.5.0-rc1 is now available.

Please can you test against your GUI code that supports v2.5.x. Business Shared Items has also been totally re-written + supports syncing of shared files to a specific local location.

**Comment by abraunegg** [comment] 2024-08-11 23:41
@bpozdena 
FYI onedrive v2.5.0-rc3 is now published. I have run this through all my use cases that I use for testing releases, and issues were fixed or test case passed.

The plan at the moment is to give this approx 1 month before the official release. Hopefully this will allow enough time for you to plan any updates / changes required for the GUI to allow for a synchronised release.

**Comment by bpozdena** [comment] 2024-08-16 08:55
Perfect. Thanks for the heads up @abraunegg .

**Comment by nerumo** [comment] 2024-09-16 04:56
In the logs, currently I get an error:

```
Client version check failed: argument of type 'int' is not iterable
```

I think thats related to the current version number of onedrive `onedrive v2.5.0-1+np1+1.1`

**Comment by ps-spark** [comment] 2024-09-16 05:33
Exactly and on the GUI it shows

![Screenshot from 2024-09-16 07-32-14](https://github.com/user-attachments/assets/be472ea1-d137-4bf5-a2b6-1bf20f62df6c)

**Comment by abraunegg** [comment] 2024-09-16 05:44
> In the logs, currently I get an error:
> 
> ```
> Client version check failed: argument of type 'int' is not iterable
> ```
> 
> I think thats related to the current version number of onedrive `onedrive v2.5.0-1+np1+1.1`

Upgrade your GUI - please read: https://github.com/bpozdena/OneDriveGUI/releases

**Comment by abraunegg** [comment] 2024-09-16 05:44
> Exactly and on the GUI it shows
> 
> ![Screenshot from 2024-09-16 07-32-14](https://private-user-images.githubusercontent.com/19947879/367656388-be472ea1-d137-4bf5-a2b6-1bf20f62df6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NjU3MDEsIm5iZiI6MTcyNjQ2NTQwMSwicGF0aCI6Ii8xOTk0Nzg3OS8zNjc2NTYzODgtYmU0NzJlYTEtZDEzNy00YmY1LWEyYjYtMWJmMjBmNjJkZjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA1NDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhOTdjMzhkNWJiMmQ5NjM5NWZiNDRjMDY2ZTQ1NGVhNmM4NWUxZGExNjFlMjQ5MjhjNWNmYWM2ZjllMmQyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m8WMn0q-ev74dH8hlB1DWJNV1rNvO-SjbhTS91kxTWE)

Upgrade your GUI - please read: https://github.com/bpozdena/OneDriveGUI/releases

**Comment by nerumo** [comment] 2024-09-16 05:47
> > In the logs, currently I get an error:
> > ```
> > Client version check failed: argument of type 'int' is not iterable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think thats related to the current version number of onedrive `onedrive v2.5.0-1+np1+1.1`
> 
> Upgrade your GUI - please read: https://github.com/bpozdena/OneDriveGUI/releases

I'm running the latest version already: OneDriveGUI-1.1.0rc3-x86_64_fc07efaee11727db6a33c765f9cc6b76.appimage

My UI doesn't look like the one from @abraunegg . But it doesn't sync anymore. I'f I press the "Play" button, it shortly goes to green, then red again. And in the logs I got the version error

**Comment by nerumo** [comment] 2024-09-16 05:50
Ok, I'm having a different problem alltogether :) I need to analyse it further.

**Comment by abraunegg** [comment] 2024-09-16 05:55
@nerumo 
> I'm running the latest version already: OneDriveGUI-1.1.0rc3-x86_64_fc07efaee11727db6a33c765f9cc6b76.appimage

Please read: https://github.com/bpozdena/OneDriveGUI/releases

GUI version [v1.0.3](https://github.com/bpozdena/OneDriveGUI/releases/tag/v1.0.3) is ONLY compatible with v2.4.x client.

GUI version [v1.1.0rc3](https://github.com/bpozdena/OneDriveGUI/releases/tag/v1.1.0rc3) is ONLY compatible with v2.5.x client.

I released v2.5.0 today ... and if you have upgraded your client, you *must* upgrade your GUI.

**Comment by nerumo** [comment] 2024-09-16 06:00
thanks @abraunegg, I am running those versions (2.5.0-1+np1+1.1 and 1.1.0rc3). Ok, my problem of not syncing was caused by the `sync_business_shared_folders` option. I thought it was related to the `Client version check failed: argument of type 'int' is not iterable`. After removing the `sync_business_shared_folders`, both seam to work now.

Thanks for your support. @bpozdena regarding the `sync_business_shared_folders`. It is documented and it's was clear to me on how to resolve it. I guess there's a reason why you don't automatically remove the `sync_business_shared_folders` option if it's set to false?

**Comment by abraunegg** [comment] 2024-09-16 06:07
@nerumo 
> After removing the sync_business_shared_folders, both seam to work now.

Please *ensure* you read the updated documentation regarding Business Shared Folders .... I hope you have fixed your local & online data *before* re-running the client ........

![image](https://github.com/user-attachments/assets/c7e5ecca-0075-4c81-a60a-2ce66352c10c)

Please read: https://github.com/abraunegg/onedrive/blob/master/docs/business-shared-items.md

**Comment by nerumo** [comment] 2024-09-16 06:43
I actually did read it. Since I'm not using any onedrive for business, I did not think that this will apply to me. That's why I'm asking my question: why do I need to do this even though I'm not using onedrive for business?

**Comment by bpozdena** [comment] 2024-09-16 06:51
I already patched it. I'll just need to run a few tests and then release the AppImage.

**Comment by ps-spark** [comment] 2024-09-16 07:10
> > Exactly and on the GUI it shows
> > ![Screenshot from 2024-09-16 07-32-14](https://private-user-images.githubusercontent.com/19947879/367656388-be472ea1-d137-4bf5-a2b6-1bf20f62df6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NjU3MDEsIm5iZiI6MTcyNjQ2NTQwMSwicGF0aCI6Ii8xOTk0Nzg3OS8zNjc2NTYzODgtYmU0NzJlYTEtZDEzNy00YmY1LWEyYjYtMWJmMjBmNjJkZjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDA1NDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhOTdjMzhkNWJiMmQ5NjM5NWZiNDRjMDY2ZTQ1NGVhNmM4NWUxZGExNjFlMjQ5MjhjNWNmYWM2ZjllMmQyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m8WMn0q-ev74dH8hlB1DWJNV1rNvO-SjbhTS91kxTWE)
> 
> Upgrade your GUI - please read: https://github.com/bpozdena/OneDriveGUI/releases

Hi @abraunegg,

Thank you. I only checked the releases but not the pre-releases :( I guess, we need GUI [v1.1.0rc3](https://github.com/bpozdena/OneDriveGUI/releases/tag/v1.1.0rc3) for client v2.5.0-1+np1+1.1.

![Screenshot from 2024-09-16 09-09-34](https://github.com/user-attachments/assets/86be4877-0d81-487a-8367-8874a4907251)

**Comment by ps-spark** [comment] 2024-09-16 07:12
> thanks @abraunegg, I am running those versions (2.5.0-1+np1+1.1 and 1.1.0rc3). Ok, my problem of not syncing was caused by the `sync_business_shared_folders` option. I thought it was related to the `Client version check failed: argument of type 'int' is not iterable`. After removing the `sync_business_shared_folders`, both seam to work now.
> 
> Thanks for your support. @bpozdena regarding the `sync_business_shared_folders`. It is documented and it's was clear to me on how to resolve it. I guess there's a reason why you don't automatically remove the `sync_business_shared_folders` option if it's set to false?

It is recommended to backup your OneDrive config directory, delete it and set it up again. There are some changes in the config files. The old config files won't work with the new version out of the box.

**Comment by bpozdena** [comment] 2024-09-16 08:08
Please test the latest [OneDriveGUI v1.1.0 AppImage](https://github.com/bpozdena/OneDriveGUI/releases/tag/v1.1.0)  and report any other issues here.

**Comment by nerumo** [comment] 2024-09-16 10:49
Tested 1.1.0. It works, no more warning/errors in the logs. Thanks

And thanks @abraunegg for the performance improvements, much faster than before

**Comment by bpozdena** [comment] 2024-09-18 10:12
Closing as completed. Please create new bug reports for any new issues.

**Closed by bpozdena** 2024-09-18 10:12 UTC
