### ISSUE TITLE
v1.1.0 fails to start onedrive v2.5.0

### ISSUE THREAD

**Issue by pablogila** [bpozdena/OneDriveGUI#181] opened 2024-09-16 19:22 UTC
With a clean install of onedrive client v2.5.0, running the GUI AppImage and clicking on the Run button does not work. Instead, after a few seconds, it stops automatically without further error logs. Clicking the Run button again has the same result.

**Comment by bpozdena** [comment] 2024-09-16 20:16
Closing for incomplete details. If you require assistance, create a new issue and provide all requested details.

**Comment by pablogila** [comment] 2024-09-17 07:00
My bad. I will provide a better description later.

**Comment by bpozdena** [comment] 2024-09-17 10:11
My bad actually. It looks like I accidentally nuked the template during the main branch merge. 

Please provide the below details:

**Describe the bug**
...issue description...

**To Reproduce**
Steps to reproduce the behavior:
1. Open OneDriveGUI by ...
2. ...
3. ...
...

**Expected behavior**
...description of expected behavior...

**Screenshots**
Provide a screenshot of the GUI showing the issue.

**Log**
If applicable, add relevant output from log file `/tmp/onedrive-gui/onedrive-gui.log`.
```
...
```

**System Info**
 - Linux distribution: [e.g. Arch Linux]
 - Desktop environment:  [e.g. KDE Plasma 6.1.4]
 - Compositor: [Wayland/X11]
 - Python version: [e.g. 3.12.3]
 - Version of OneDrive client: [e.g. 2.5.0]

**OneDriveGUI info**
How did you install OneDriveGUI?: [e.g. AppImage]
What is the name of the AppImage file (if applicable)? : [e.g.  OneDriveGUI-1.1.0-x86_64.AppImage ]

**Comment by guillaume-mueller** [comment] 2024-09-18 17:42
I had the same issue.

I removed my profile and put if back, then restarted the application and it worked. I had not tested to only restart the application so I'm not sure resetting my profile was required.

**Comment by pablogila** [comment] 2024-09-19 22:42
Thanks! Restarting the app did not work, but removing the profile and creating it again worked fine. Perhaps a warning could be added to the documentation if the devs feel it is appropriate.

**Comment by marty-macfly** [comment] 2024-09-23 19:39
It seems tag v1.1.0 is pointing to code version that doesn't detect version 2.5.0 properly, so may be another source of that issue ? https://github.com/bpozdena/OneDriveGUI/blob/8c5b75f87ae402cb7e2ffa9b0ab0e5bba7182e56/src/OneDriveGUI.py#L164

**Closed** 2024-09-26 13:56 UTC
