### ISSUE TITLE
won't minimise to tray if program runs before dock initialises

### ISSUE THREAD

**Issue by TheAwesome98-Real** [bpozdena/OneDriveGUI#180] opened 2024-09-03 15:22 UTC
**Describe the bug**
if onedrivegui opens before the tray initialises, it won't minimise to it

**To Reproduce**
- open onedrivegui
- open your tray
- close onedrivegui with the titlebar button
- it minimises instead of closes

**Expected behavior**
i expected it to minimise to the tray

**Screenshots**

**Log**
If applicable, add relevant output from log file `/tmp/onedrive-gui/onedrive-gui.log`.

**System Info**
 - Linux distribution: [e.g. Ubuntu 22.04] NixOS 24.05 Uakari
 - Desktop environment:  [e.g. Gnome] MATE
 - Compositor: [e.g. Wayland] X11 (is this what you mean? that's called a window server)
 - Python version: [e.g. 3.11] 3.11.9 (i think)
 - Version of OneDrive client [e.g. v2.4.25] v2.4.25
or output of below commands:
```sh
lsb_release -a
echo $XDG_CURRENT_DESKTOP
loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}'
python --version
which onedrive
onedrive --version
```

**OneDriveGUI info**
How did you install OneDriveGUI?: [AppImage/source/AUR] nixpkgs
What is the name of the AppImage file (if applicable)? : [e.g OneDriveGUI-1.x.x-x86_64.AppImage]

**Additional context**

**Comment by bpozdena** [comment] 2024-09-03 16:19
Hi @TheAwesome98-Real , 

my understanding is that OneDriveGUI starts before your system tray is be initialized after boot.  If that is correct, then  OneDriveGUI behaves as expected. 

The problem is that if the tray is not available and the OneDriveGUI minimizes "to it", you will never be able to open the window again. 

If your system tray starts working with a delay for some reason, perhaps you could simply delay the start of OneDriveGUI by a few seconds?

Alternatively, you might need to tweak MATE settings to ensure [StatusNotifierItem](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/) is working as expected. I don't know anything about MATE, but it looks like the system tray functionality can be achieved with [Ayatana Indicators](https://github.com/AyatanaIndicators/ayatana-indicator-display) .

**Comment by TheAwesome98-Real** [comment] 2024-09-03 17:14
i could delay onedrivegui's startup, but i was wondering if you could make a setting for delaying connecting to the tray? i don't know how the tray in x11 works, so i don't know if this is possible.

**Comment by bpozdena** [comment] 2024-09-03 18:46
There is no way to implement it without periodically checking if the tray become available. The end result would be weird as the GUI would first minimize into dock and then suddenly disappear from there. 

I'd suggest delaying the OnedriveGUI start, or fixing your desktop environment and ensuring the tray applet loads before other apps. 

I'll close this as not planned.

**Closed by bpozdena** 2024-09-03 18:46 UTC
