### ISSUE TITLE
OneDrive GUI stuck on initializing API for onedrive business account.

### ISSUE THREAD

**Issue by Navknight** [bpozdena/OneDriveGUI#115] opened 2023-08-19 01:20 UTC
The Onedrive GUI app has been stuck on initialising API for a onedrive business account. The terminal commands however work perfectly

`onedrive --synchronize` works without any error but the GUI app is stuck on initializing API

**Comment by bpozdena** [comment] 2023-08-19 08:40
@Navknight please share the console logs. If you're using appimage, run it from terminal to see the outputs.

**Comment by WayneCoombes** [comment] 2023-09-05 18:00
I installed OneDriveGUI-1.0.3_fix116-x86_64.AppImage on two Linux Mint Cinnamon 21.2 machines yesterday. On the desktop this is working as expected. On the laptop once I successfully perform the OneDrive connection and endeavor to start sync the GUI tells me an application configuration change has been detected and a re-sync is required, and if I proceed I go through the same process again.

**Comment by Navknight** [comment] 2023-09-12 06:45
> @Navknight please share the console logs. If you're using appimage, run it from terminal to see the outputs.


```
[navknight@fedora Applications]$ ./OneDriveGUI-1.0.3_fix116-x86_64_cc12481865dd312f40ff25e26fe2f8f1.AppImage 
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
QSocketNotifier: Can only be used with threads started with QThread
qt.qpa.qgnomeplatform.theme: The desktop style for QtQuick Controls 2 applications is not available on the system (qqc2-desktop-style). The application may look broken.
2023-09-12 12:14:02,407 [OneDriveGUI.py:3093][fn=config_client_bin_path][INFO] - Onedrive client location: 'onedrive'
2023-09-12 12:14:02,416 [OneDriveGUI.py:2854][fn=get_installed_client_version][DEBUG] - [GUI] Installed client version is 2425
2023-09-12 12:14:02,417 [OneDriveGUI.py:2889][fn=create_global_config][DEBUG] - [GUI] - loading default config {'onedrive': {'sync_dir': '"~/OneDrive"', 'monitor_interval': '"300"', 'log_dir': '"/var/log/onedrive/"', 'drive_id': '""', 'upload_only': '"false"', 'check_nomount': '"false"', 'check_nosync': '"false"', 'download_only': '"false"', 'disable_notifications': '"false"', 'disable_upload_validation': '"false"', 'enable_logging': '"false"', 'force_http_11': '"false"', 'local_first': '"false"', 'no_remote_delete': '"false"', 'skip_symlinks': '"false"', 'debug_https': '"false"', 'skip_dotfiles': '"false"', 'dry_run': '"false"', 'min_notify_changes': '"5"', 'monitor_log_frequency': '"5"', 'monitor_fullscan_frequency': '"10"', 'sync_root_files': '"false"', 'classify_as_big_delete': '"1000"', 'user_agent': '""', 'remove_source_files': '"false"', 'skip_dir_strict_match': '"false"', 'application_id': '""', 'resync': '"false"', 'bypass_data_preservation': '"false"', 'azure_ad_endpoint': '""', 'azure_tenant_id': '"common"', 'sync_business_shared_folders': '"false"', 'sync_dir_permissions': '"700"', 'sync_file_permissions': '"600"', 'rate_limit': '"125000000"', 'operation_timeout': '"3600"', 'webhook_enabled': '"false"', 'webhook_public_url': '""', 'webhook_listening_host': '""', 'webhook_listening_port': '"8888"', 'webhook_expiration_interval': '"86400"', 'webhook_renewal_interval': '"43200"', 'skip_file': '"~*|.~*|*.tmp"', 'skip_dir': '""'}}
2023-09-12 12:14:02,417 [OneDriveGUI.py:2933][fn=create_global_config][DEBUG] - [GUI]{'OD': {'config_file': '/home/navknight/.config/onedrive/accounts/OD/config', 'auto_sync': 'True', 'account_type': 'Business', 'free_space': '906.1GiB', 'onedrive': {'sync_dir': '"/home/navknight"', 'monitor_interval': '"300"', 'log_dir': '"/var/log/onedrive/"', 'drive_id': '""', 'upload_only': '"false"', 'check_nomount': '"false"', 'check_nosync': '"false"', 'download_only': '"false"', 'disable_notifications': '"false"', 'disable_upload_validation': '"false"', 'enable_logging': '"false"', 'force_http_11': '"false"', 'local_first': '"false"', 'no_remote_delete': '"false"', 'skip_symlinks': '"false"', 'debug_https': '"false"', 'skip_dotfiles': '"true"', 'dry_run': '"false"', 'min_notify_changes': '"5"', 'monitor_log_frequency': '"5"', 'monitor_fullscan_frequency': '"10"', 'sync_root_files': '"false"', 'classify_as_big_delete': '"1000"', 'user_agent': '""', 'remove_source_files': '"false"', 'skip_dir_strict_match': '"false"', 'application_id': '""', 'resync': '"false"', 'bypass_data_preservation': '"false"', 'azure_ad_endpoint': '""', 'azure_tenant_id': '"common"', 'sync_business_shared_folders': '"false"', 'sync_dir_permissions': '"700"', 'sync_file_permissions': '"600"', 'rate_limit': '"125000000"', 'operation_timeout': '"3600"', 'webhook_enabled': '"false"', 'webhook_public_url': '""', 'webhook_listening_host': '""', 'webhook_listening_port': '"8888"', 'webhook_expiration_interval': '"86400"', 'webhook_renewal_interval': '"43200"', 'skip_file': '"~*|.~*|*.tmp"', 'skip_dir': '"|Downloads|Github|Public|Android|Applications|Music|Videos|Templates|Pictures"'}}}
2023-09-12 12:14:02,418 [OneDriveGUI.py:2942][fn=save_global_config][DEBUG] - [save_global_config]:[1]{'OD': {'config_file': '/home/navknight/.config/onedrive/accounts/OD/config', 'auto_sync': 'True', 'account_type': 'Business', 'free_space': '906.1GiB', 'onedrive': {'sync_dir': '"/home/navknight"', 'monitor_interval': '"300"', 'log_dir': '"/var/log/onedrive/"', 'drive_id': '""', 'upload_only': '"false"', 'check_nomount': '"false"', 'check_nosync': '"false"', 'download_only': '"false"', 'disable_notifications': '"false"', 'disable_upload_validation': '"false"', 'enable_logging': '"false"', 'force_http_11': '"false"', 'local_first': '"false"', 'no_remote_delete': '"false"', 'skip_symlinks': '"false"', 'debug_https': '"false"', 'skip_dotfiles': '"true"', 'dry_run': '"false"', 'min_notify_changes': '"5"', 'monitor_log_frequency': '"5"', 'monitor_fullscan_frequency': '"10"', 'sync_root_files': '"false"', 'classify_as_big_delete': '"1000"', 'user_agent': '""', 'remove_source_files': '"false"', 'skip_dir_strict_match': '"false"', 'application_id': '""', 'resync': '"false"', 'bypass_data_preservation': '"false"', 'azure_ad_endpoint': '""', 'azure_tenant_id': '"common"', 'sync_business_shared_folders': '"false"', 'sync_dir_permissions': '"700"', 'sync_file_permissions': '"600"', 'rate_limit': '"125000000"', 'operation_timeout': '"3600"', 'webhook_enabled': '"false"', 'webhook_public_url': '""', 'webhook_listening_host': '""', 'webhook_listening_port': '"8888"', 'webhook_expiration_interval': '"86400"', 'webhook_renewal_interval': '"43200"', 'skip_file': '"~*|.~*|*.tmp"', 'skip_dir': '"|Downloads|Github|Public|Android|Applications|Music|Videos|Templates|Pictures"'}}}
2023-09-12 12:14:02,424 [OneDriveGUI.py:2998][fn=save_global_config][INFO] - OD config saved
2023-09-12 12:14:02,424 [OneDriveGUI.py:3000][fn=save_global_config][INFO] - All configs saved
2023-09-12 12:14:02,424 [OneDriveGUI.py:3001][fn=save_global_config][DEBUG] - {'OD': {'config_file': '/home/navknight/.config/onedrive/accounts/OD/config', 'auto_sync': 'True', 'account_type': 'Business', 'free_space': '906.1GiB', 'onedrive': {'sync_dir': '"/home/navknight"', 'monitor_interval': '"300"', 'log_dir': '"/var/log/onedrive/"', 'drive_id': '""', 'upload_only': '"false"', 'check_nomount': '"false"', 'check_nosync': '"false"', 'download_only': '"false"', 'disable_notifications': '"false"', 'disable_upload_validation': '"false"', 'enable_logging': '"false"', 'force_http_11': '"false"', 'local_first': '"false"', 'no_remote_delete': '"false"', 'skip_symlinks': '"false"', 'debug_https': '"false"', 'skip_dotfiles': '"true"', 'dry_run': '"false"', 'min_notify_changes': '"5"', 'monitor_log_frequency': '"5"', 'monitor_fullscan_frequency': '"10"', 'sync_root_files': '"false"', 'classify_as_big_delete': '"1000"', 'user_agent': '""', 'remove_source_files': '"false"', 'skip_dir_strict_match': '"false"', 'application_id': '""', 'resync': '"false"', 'bypass_data_preservation': '"false"', 'azure_ad_endpoint': '""', 'azure_tenant_id': '"common"', 'sync_business_shared_folders': '"false"', 'sync_dir_permissions': '"700"', 'sync_file_permissions': '"600"', 'rate_limit': '"125000000"', 'operation_timeout': '"3600"', 'webhook_enabled': '"false"', 'webhook_public_url': '""', 'webhook_listening_host': '""', 'webhook_listening_port': '"8888"', 'webhook_expiration_interval': '"86400"', 'webhook_renewal_interval': '"43200"', 'skip_file': '"~*|.~*|*.tmp"', 'skip_dir': '"|Downloads|Github|Public|Android|Applications|Music|Videos|Templates|Pictures"'}}}
Requested decoration  "gnome"  not found, falling back to default
Requested decoration  "gnome"  not found, falling back to default
2023-09-12 12:14:02,648 [OneDriveGUI.py:3019][fn=main_window_start_state][INFO] - [GUI] Starting OneDriveGUI maximized
2023-09-12 12:14:02,649 [OneDriveGUI.py:1098][fn=__init__][INFO] - OD
Requested decoration  "gnome"  not found, falling back to default
Gtk-Message: 12:14:02.674: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:14:02.674: Failed to load module "pk-gtk-module"
2023-09-12 12:14:03,138 [connectionpool.py:1014][fn=_new_conn][DEBUG] - Starting new HTTPS connection (1): api.github.com:443
2023-09-12 12:14:03,851 [connectionpool.py:473][fn=_make_request][DEBUG] - https://api.github.com:443 "GET /repos/abraunegg/onedrive/releases/latest HTTP/1.1" 200 1197
2023-09-12 12:14:03,876 [OneDriveGUI.py:2472][fn=client_version_check][DEBUG] - [GUI] Client version check: {'latest_client_version': 'v2.4.25', 'installed_client_version': 'v2.4.25'}
2023-09-12 12:14:03,889 [OneDriveGUI.py:2545][fn=autostart_monitor][DEBUG] - [OD] Compatible client version found: True
2023-09-12 12:14:03,889 [OneDriveGUI.py:2546][fn=autostart_monitor][DEBUG] - [OD] Auto-sync enabled for profile: True
2023-09-12 12:14:03,889 [OneDriveGUI.py:2024][fn=__init__][INFO] - [GUI] Starting worker for profile OD
2023-09-12 12:14:03,889 [OneDriveGUI.py:2028][fn=__init__][DEBUG] - [GUI] OneDrive config file: /home/navknight/.config/onedrive/accounts/OD/config
2023-09-12 12:14:03,889 [OneDriveGUI.py:2029][fn=__init__][DEBUG] - [GUI] OneDrive config dir: <re.Match object; span=(0, 51), match='/home/navknight/.config/onedrive/accounts/OD/conf>
2023-09-12 12:14:03,889 [OneDriveGUI.py:2031][fn=__init__][DEBUG] - [GUI] Monitoring command: 'exec onedrive --confdir='/home/navknight/.config/onedrive/accounts/OD' --monitor -v '
2023-09-12 12:14:03,889 [OneDriveGUI.py:2561][fn=start_onedrive_monitor][INFO] - [GUI] Opening external login window
2023-09-12 12:14:03,897 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Using 'user' Config Dir: /home/navknight/.config/onedrive/accounts/OD
2023-09-12 12:14:03,897 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Using config option for Global Azure AD Endpoints
2023-09-12 12:14:03,897 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Configuration file successfully loaded
2023-09-12 12:14:07,474 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Checking Application Version ...
2023-09-12 12:14:10,438 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Initializing the OneDrive API ...
2023-09-12 12:14:10,438 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Configuring Global Azure AD Endpoints
2023-09-12 12:14:10,439 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Using Curl defaults for all HTTP operations
2023-09-12 12:14:10,439 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] User Configured Rate Limit: 125000000
2023-09-12 12:14:10,439 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Opening the item database ...
2023-09-12 12:14:10,459 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] All operations will be performed in: /home/navknight
2023-09-12 12:14:17,582 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Application version: v2.4.25
2023-09-12 12:14:17,582 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Account Type: business
2023-09-12 12:14:17,583 [OneDriveGUI.py:2135][fn=read_stdout][INFO] - [OD] Account type: business
2023-09-12 12:14:17,584 [OneDriveGUI.py:2942][fn=save_global_config][DEBUG] - [save_global_config]:[1]{'OD': {'config_file': '/home/navknight/.config/onedrive/accounts/OD/config', 'auto_sync': 'True', 'account_type': 'Business', 'free_space': '906.1GiB', 'onedrive': {'sync_dir': '"/home/navknight"', 'monitor_interval': '"300"', 'log_dir': '"/var/log/onedrive/"', 'drive_id': '""', 'upload_only': '"false"', 'check_nomount': '"false"', 'check_nosync': '"false"', 'download_only': '"false"', 'disable_notifications': '"false"', 'disable_upload_validation': '"false"', 'enable_logging': '"false"', 'force_http_11': '"false"', 'local_first': '"false"', 'no_remote_delete': '"false"', 'skip_symlinks': '"false"', 'debug_https': '"false"', 'skip_dotfiles': '"true"', 'dry_run': '"false"', 'min_notify_changes': '"5"', 'monitor_log_frequency': '"5"', 'monitor_fullscan_frequency': '"10"', 'sync_root_files': '"false"', 'classify_as_big_delete': '"1000"', 'user_agent': '""', 'remove_source_files': '"false"', 'skip_dir_strict_match': '"false"', 'application_id': '""', 'resync': '"false"', 'bypass_data_preservation': '"false"', 'azure_ad_endpoint': '""', 'azure_tenant_id': '"common"', 'sync_business_shared_folders': '"false"', 'sync_dir_permissions': '"700"', 'sync_file_permissions': '"600"', 'rate_limit': '"125000000"', 'operation_timeout': '"3600"', 'webhook_enabled': '"false"', 'webhook_public_url': '""', 'webhook_listening_host': '""', 'webhook_listening_port': '"8888"', 'webhook_expiration_interval': '"86400"', 'webhook_renewal_interval': '"43200"', 'skip_file': '"~*|.~*|*.tmp"', 'skip_dir': '"|Downloads|Github|Public|Android|Applications|Music|Videos|Templates|Pictures"'}}}
2023-09-12 12:14:17,598 [OneDriveGUI.py:2998][fn=save_global_config][INFO] - OD config saved
2023-09-12 12:14:17,598 [OneDriveGUI.py:3000][fn=save_global_config][INFO] - All configs saved
2023-09-12 12:14:17,598 [OneDriveGUI.py:3001][fn=save_global_config][DEBUG] - {'OD': {'config_file': '/home/navknight/.config/onedrive/accounts/OD/config', 'auto_sync': 'True', 'account_type': 'Business', 'free_space': '906.1GiB', 'onedrive': {'sync_dir': '"/home/navknight"', 'monitor_interval': '"300"', 'log_dir': '"/var/log/onedrive/"', 'drive_id': '""', 'upload_only': '"false"', 'check_nomount': '"false"', 'check_nosync': '"false"', 'download_only': '"false"', 'disable_notifications': '"false"', 'disable_upload_validation': '"false"', 'enable_logging': '"false"', 'force_http_11': '"false"', 'local_first': '"false"', 'no_remote_delete': '"false"', 'skip_symlinks': '"false"', 'debug_https': '"false"', 'skip_dotfiles': '"true"', 'dry_run': '"false"', 'min_notify_changes': '"5"', 'monitor_log_frequency': '"5"', 'monitor_fullscan_frequency': '"10"', 'sync_root_files': '"false"', 'classify_as_big_delete': '"1000"', 'user_agent': '""', 'remove_source_files': '"false"', 'skip_dir_strict_match': '"false"', 'application_id': '""', 'resync': '"false"', 'bypass_data_preservation': '"false"', 'azure_ad_endpoint': '""', 'azure_tenant_id': '"common"', 'sync_business_shared_folders': '"false"', 'sync_dir_permissions': '"700"', 'sync_file_permissions': '"600"', 'rate_limit': '"125000000"', 'operation_timeout': '"3600"', 'webhook_enabled': '"false"', 'webhook_public_url': '""', 'webhook_listening_host': '""', 'webhook_listening_port': '"8888"', 'webhook_expiration_interval': '"86400"', 'webhook_renewal_interval': '"43200"', 'skip_file': '"~*|.~*|*.tmp"', 'skip_dir': '"|Downloads|Github|Public|Android|Applications|Music|Videos|Templates|Pictures"'}}}
2023-09-12 12:14:17,598 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Default Drive ID: b!MingJHlSH0WN2W0t9BCRBZmaltJqKf9KguaGE4gSXE0vjMqp40m-TKooSfUQDaPT
2023-09-12 12:14:17,598 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Default Root ID: 01CCY6XQN6Y2GOVW7725BZO354PWSELRRZ
2023-09-12 12:14:17,599 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Remaining Free Space: 972906475904
2023-09-12 12:14:17,599 [OneDriveGUI.py:2123][fn=read_stdout][INFO] - [OD] Free Space: 906.1GiB
2023-09-12 12:14:17,599 [OneDriveGUI.py:2942][fn=save_global_config][DEBUG] - [save_global_config]:[1]{'OD': {'config_file': '/home/navknight/.config/onedrive/accounts/OD/config', 'auto_sync': 'True', 'account_type': 'Business', 'free_space': '906.1GiB', 'onedrive': {'sync_dir': '"/home/navknight"', 'monitor_interval': '"300"', 'log_dir': '"/var/log/onedrive/"', 'drive_id': '""', 'upload_only': '"false"', 'check_nomount': '"false"', 'check_nosync': '"false"', 'download_only': '"false"', 'disable_notifications': '"false"', 'disable_upload_validation': '"false"', 'enable_logging': '"false"', 'force_http_11': '"false"', 'local_first': '"false"', 'no_remote_delete': '"false"', 'skip_symlinks': '"false"', 'debug_https': '"false"', 'skip_dotfiles': '"true"', 'dry_run': '"false"', 'min_notify_changes': '"5"', 'monitor_log_frequency': '"5"', 'monitor_fullscan_frequency': '"10"', 'sync_root_files': '"false"', 'classify_as_big_delete': '"1000"', 'user_agent': '""', 'remove_source_files': '"false"', 'skip_dir_strict_match': '"false"', 'application_id': '""', 'resync': '"false"', 'bypass_data_preservation': '"false"', 'azure_ad_endpoint': '""', 'azure_tenant_id': '"common"', 'sync_business_shared_folders': '"false"', 'sync_dir_permissions': '"700"', 'sync_file_permissions': '"600"', 'rate_limit': '"125000000"', 'operation_timeout': '"3600"', 'webhook_enabled': '"false"', 'webhook_public_url': '""', 'webhook_listening_host': '""', 'webhook_listening_port': '"8888"', 'webhook_expiration_interval': '"86400"', 'webhook_renewal_interval': '"43200"', 'skip_file': '"~*|.~*|*.tmp"', 'skip_dir': '"|Downloads|Github|Public|Android|Applications|Music|Videos|Templates|Pictures"'}}}
2023-09-12 12:14:17,609 [OneDriveGUI.py:2998][fn=save_global_config][INFO] - OD config saved
2023-09-12 12:14:17,609 [OneDriveGUI.py:3000][fn=save_global_config][INFO] - All configs saved
2023-09-12 12:14:17,610 [OneDriveGUI.py:3001][fn=save_global_config][DEBUG] - {'OD': {'config_file': '/home/navknight/.config/onedrive/accounts/OD/config', 'auto_sync': 'True', 'account_type': 'Business', 'free_space': '906.1GiB', 'onedrive': {'sync_dir': '"/home/navknight"', 'monitor_interval': '"300"', 'log_dir': '"/var/log/onedrive/"', 'drive_id': '""', 'upload_only': '"false"', 'check_nomount': '"false"', 'check_nosync': '"false"', 'download_only': '"false"', 'disable_notifications': '"false"', 'disable_upload_validation': '"false"', 'enable_logging': '"false"', 'force_http_11': '"false"', 'local_first': '"false"', 'no_remote_delete': '"false"', 'skip_symlinks': '"false"', 'debug_https': '"false"', 'skip_dotfiles': '"true"', 'dry_run': '"false"', 'min_notify_changes': '"5"', 'monitor_log_frequency': '"5"', 'monitor_fullscan_frequency': '"10"', 'sync_root_files': '"false"', 'classify_as_big_delete': '"1000"', 'user_agent': '""', 'remove_source_files': '"false"', 'skip_dir_strict_match': '"false"', 'application_id': '""', 'resync': '"false"', 'bypass_data_preservation': '"false"', 'azure_ad_endpoint': '""', 'azure_tenant_id': '"common"', 'sync_business_shared_folders': '"false"', 'sync_dir_permissions': '"700"', 'sync_file_permissions': '"600"', 'rate_limit': '"125000000"', 'operation_timeout': '"3600"', 'webhook_enabled': '"false"', 'webhook_public_url': '""', 'webhook_listening_host': '""', 'webhook_listening_port': '"8888"', 'webhook_expiration_interval': '"86400"', 'webhook_renewal_interval': '"43200"', 'skip_file': '"~*|.~*|*.tmp"', 'skip_dir': '"|Downloads|Github|Public|Android|Applications|Music|Videos|Templates|Pictures"'}}}
2023-09-12 12:14:17,610 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Fetching details for OneDrive Root
2023-09-12 12:14:17,712 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] OneDrive Root exists in the database
2023-09-12 12:14:17,712 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Initializing the Synchronization Engine ...
2023-09-12 12:14:17,713 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Initializing monitor ...
2023-09-12 12:14:17,713 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] OneDrive monitor interval (seconds): 300
2023-09-12 12:14:17,713 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Monitor directory: .
2023-09-12 12:14:19,757 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Calling Function: addRecursive()
2023-09-12 12:14:19,757 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Calling Function: addRecursive()
2023-09-12 12:14:19,757 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Calling Function: addRecursive()
2023-09-12 12:14:19,757 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Calling Function: addRecursive()
2023-09-12 12:14:19,757 [OneDriveGUI.py:2100][fn=read_stdout][INFO] - [OD] Calling Function: addRecursive()

```

after this it's just the addRecursive() call again and again

**Comment by Navknight** [comment] 2023-09-12 06:46
Side note - The sync works on the "Download only" option. So there's an issue with upload

**Comment by bpozdena** [comment] 2023-09-12 07:00
I find it strange that your sync dir is your entire home directory `/home/navknight`. 

Please run sync from terminal using the bellow command and provide the entire output:
`onedrive --confdir='/home/navknight/.config/onedrive/accounts/OD' --monitor -v`

**Comment by Navknight** [comment] 2023-09-12 07:06
> I find it strange that your sync dir is your entire home directory `/home/navknight`.
> 
> Please run sync from terminal using the bellow command and provide the entire output: `onedrive --confdir='/home/navknight/.config/onedrive/accounts/OD' --monitor -v`

```
onedrive --confdir='/home/navknight/.config/onedrive/accounts/OD' --monitor -v
Using 'user' Config Dir: /home/navknight/.config/onedrive/accounts/OD
Using config option for Global Azure AD Endpoints
Configuration file successfully loaded
Checking Application Version ...
Initializing the OneDrive API ...
Configuring Global Azure AD Endpoints
Using Curl defaults for all HTTP operations
User Configured Rate Limit: 125000000
Opening the item database ...
All operations will be performed in: /home/navknight
Application version: v2.4.25
Account Type: business
Default Drive ID: b!MingJHlSH0WN2W0t9BCRBZmaltJqKf9KguaGE4gSXE0vjMqp40m-TKooSfUQDaPT
Default Root ID: 01CCY6XQN6Y2GOVW7725BZO354PWSELRRZ
Remaining Free Space: 972906475319
Fetching details for OneDrive Root
OneDrive Root exists in the database
Initializing the Synchronization Engine ...
Initializing monitor ...
OneDrive monitor interval (seconds): 300
Monitor directory: .

ERROR: The local file system returned an error with the following message:
  Error Message:    ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/gnome-maps/flatpak/staging/x86_64-main/var/run/gdm: Permission denied
  Calling Function: addRecursive()


ERROR: The local file system returned an error with the following message:
  Error Message:    ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/gnome-maps/flatpak/staging/x86_64-main/var/run/firewalld: Permission denied
  Calling Function: addRecursive()


ERROR: The local file system returned an error with the following message:
  Error Message:    ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/gnome-maps/flatpak/staging/x86_64-main/var/run/udisks2: Permission denied
  Calling Function: addRecursive()


ERROR: The local file system returned an error with the following message:
  Error Message:    ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/gnome-maps/flatpak/staging/x86_64-main/var/run/chrony: Permission denied
  Calling Function: addRecursive()


ERROR: The local file system returned an error with the following message:
  Error Message:    ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/gnome-maps/flatpak/staging/x86_64-main/var/run/libvirt/qemu/dbus: Permission denied
  Calling Function: addRecursive()


ERROR: The local file system returned an error with the following message:
  Error Message:    ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/gnome-maps/flatpak/staging/x86_64-main/var/run/libvirt/common: Permission denied
  Calling Function: addRecursive()


ERROR: The local file system returned an error with the following message:
  Error Message:    ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/gnome-maps/flatpak/staging/x86_64-main/var/run/host/boot/grub2: Permission denied
  Calling Function: addRecursive()


ERROR: The local file system returned an error with the following message:
  Error Message:    ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/gnome-maps/flatpak/staging/x86_64-main/var/run/host/boot/lost+found: Permission denied
  Calling Function: addRecursive()


ERROR: The local file system returned an error with the following message:
  Error Message:    ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/gnome-maps/flatpak/staging/x86_64-main/var/run/host/boot/loader/entries: Permission denied
  Calling Function: addRecursive()


ERROR: The local file system returned an error with the following message:
  Error Message:    ./.var/app/org.gnome.Builder/cache/gnome-builder/projects/gnome-maps/flatpak/staging/x86_64-main/var/run/host/boot/efi: Permission denied
  Calling Function: addRecursive()
```

I have the home directory as the sync folder because I wanted to sync all my files to onedrive excluding the hidden ones. It's strange but it used to get the job done.

**Comment by bpozdena** [comment] 2023-09-12 07:28
Thanks for the confirmation. You will need to add the affected directories into exclusion list if you really insist on syncing the entire home directory for some reason. 

Since the problem is not related to the GUI, I'm closing this issue.

**Closed by bpozdena** 2023-09-12 07:28 UTC
