### ISSUE TITLE
cannot access settings

### ISSUE THREAD

**Issue by JRSV** [bpozdena/OneDriveGUI#39] opened 2022-06-29 17:19 UTC
Linux distribution and version: AVL-MX (debian 10)
Desktop environment and version: XFCE 4
Display Server (X11/Wayland): X11
Are you using Appimage or running the GUI from source? source
Do you have "start minimized" feature enabled in the GUI?no

I cannot enter the settings tab. If the app is running and I click on the icon, I can see the grey menu with the settings option, however it disappears in less then a second. so I cannot access the settings.

I also saw in another post about the transparent settings window, this also happens the first time onedrive gui runs.

**Comment by bpozdena** [comment] 2022-06-30 12:49
I tried to reproduce with mixed results. 

1) When you are talking about a "gray menu" are you referring to system tray context menu as shown bellow? I could not reproduce any issues on AVL-MX 21.0 . I however occasionally come across this issue on KDE Plasma. I will try to fix the issue on Plasma and hopefully it will fixe it for you too on XFCE. 
![image](https://user-images.githubusercontent.com/24818591/176668472-99f52960-81ac-4b6a-8c5f-7ac0ab8baa53.png)

2)I could not get the settings window open at all. I'm guessing it's some incompatibility with Openbox WM. Also when I used Xfwm, I could see the transparent settings window on startup (reported in #38). I will see what I can do about this.

**Comment by JRSV** [comment] 2022-07-04 13:29
Hello @bpozdena 

1. Yes, that is the menu,I am going to upgrade sometime soon, but its a bit complicated for me now. so nothing in the near future. 
2. I cant get it open at all, 
cheers

**Comment by bpozdena** [comment] 2022-07-22 20:12
@JRSV , can you please try the latest AppImage build https://github.com/bpozdena/OneDriveGUI/releases/download/v0.2.2/OneDriveGUI-0.2.2-fix41-x86_64.AppImage ?

**Comment by JRSV** [comment] 2022-07-23 13:36
@bpozdena 

it still has the problem although I could sporadically get the manu to not disappear, it keeps doing it most of the time. The little menu that should stay visible just disappears.

![onedrive](https://user-images.githubusercontent.com/18346930/180607385-32bc7c28-f8ea-4f01-af2d-37baed03c912.gif)

**Comment by bpozdena** [comment] 2022-07-23 21:07
Thanks for the gif @JRSV .  Even though I can't quite reproduce the issue, I think I understand the problem now. I made a theoretical fix in the bellow AppImage. Please test it and let me know if you noticed some improvements. 

https://github.com/bpozdena/OneDriveGUI/releases/download/v0.2.2/OneDriveGUI-0.2.2-fix39-x86_64.AppImage

**Comment by JRSV** [comment] 2022-07-24 02:33
great!! this one works perfect on initial tests.
thanks

**Comment by bpozdena** [comment] 2022-07-24 10:54
Thanks for reporting and testing! I will be closing this issue for now.

**Closed by bpozdena** 2022-07-24 10:54 UTC
Labels: bug
