### ISSUE TITLE
Ubuntu launcher icon not working

### ISSUE THREAD

**Issue by derek-shnosh** [bpozdena/OneDriveGUI#161] opened 2024-04-05 17:26 UTC
**Describe the bug**
The launcher icon does not load, tray icon works fine. I installed/integrated the .appimage file with [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher).

**To Reproduce**
Steps to reproduce the behavior: Download release, double click and let  "integrate and run" it.

**Expected behavior**
The defined icon should be displayed in the launcher or dash.

**Screenshots**
![image](https://github.com/bpozdena/OneDriveGUI/assets/21090563/b68cbddf-44fb-449b-954a-9e614ef86193)

**Log**
Not applicable.

**System Info**
 - Linux distribution: Ubuntu 23.10
 - Desktop environment:  GNOME 45.2
 - Compositor: Wayland
 - Python version: 3.11.6
 - Version of OneDrive client: v2.4.25-1+np2+4.1
 - Version of AppImageLauncher: 202211022348-stable-0f91801~ubuntu22.10.1

**OneDriveGUI info**
How did you install OneDriveGUI?: AppImage
What is the name of the AppImage file (if applicable)?:
- Downloaded: OneDriveGUI-1.0.3_fix116-x86_64.AppImage
- *Installed* by AppImageLauncher: OneDriveGUI-1.0.3_fix116-x86_64_cc12481865dd312f40ff25e26fe2f8f1.AppImage

**Additional context**
Contents of .desktop file (`~/.local/share/applications/appimagekit_f3679f5fc4c8c71d3bc97b1cb17d1f39-OneDriveGUI.desktop`)

```
[Desktop Entry]
X-AppImage-Arch=x86_64
X-AppImage-Version=1.0.3_fix116
X-AppImage-Name=OneDriveGUI
Name=OneDriveGUI (1.0.3_fix116)
Exec=/home/ds/Applications/OneDriveGUI-1.0.3_fix116-x86_64_cc12481865dd312f40ff25e26fe2f8f1.AppImage
Icon=appimagekit_f3679f5fc4c8c71d3bc97b1cb17d1f39_OneDriveGUI
Type=Application
Terminal=false
Categories=Utility;
Comment=

TryExec=/home/ds/Applications/OneDriveGUI-1.0.3_fix116-x86_64_cc12481865dd312f40ff25e26fe2f8f1.AppImage
X-AppImage-Old-Icon=OneDriveGUI
X-AppImage-Old-Name=OneDriveGUI
X-AppImage-Identifier=f3679f5fc4c8c71d3bc97b1cb17d1f39
Actions=Remove;
X-AppImageLauncher-Version=2.2.0 (git commit 0f91801), built on 2020-09-29 21:36:15 UTC

[Desktop Action Remove]
Name=Remove AppImage from system
Icon=AppImageLauncher
Exec=/usr/lib/x86_64-linux-gnu/appimagelauncher/remove "/home/ds/Applications/OneDriveGUI-1.0.3_fix116-x86_64_cc12481865dd312f40ff25e26fe2f8f1.AppImage"
Name[ast]=Desaniciar AppImage del sistema
Name[cs]=Odebrat AppImage ze systému
Name[de]=AppImage vom System entfernen
Name[en]=Remove AppImage from system
Name[es]=Eliminar Appimage del Sistema
Name[fr]=Supprimer l'AppImage du système
Name[it]=Rimuovi AppImage dal sistema
Name[nl]=AppImage deïnstalleren
Name[pl]=Usuń AppImage z systemu
Name[pt]=Remover AppImage do sistema
Name[pt_PT]=Remover AppImage do sistema
Name[ru]=Удалить AppImage из системы
Name[zh_Hans]=从系统中移除 AppImage
```

**Comment by bpozdena** [comment] 2024-04-12 20:15
I don't taking it's solvable for AppImages on Wayland at the moment, just like #148 . The only workaround would be to use X11.

I'll keep it open for now and see if there is a solution from Wayland devs in the future.

**Comment by bpozdena** [comment] 2024-09-18 10:05
Closing as duplicate of https://github.com/bpozdena/OneDriveGUI/issues/148 for now. The issue will be tracked there.

**Closed by bpozdena** 2024-09-18 10:05 UTC

**Comment by theblackhole** [comment] 2025-05-09 21:01
This issue is different than #148 : the window icon works here, it's the launcher icon that doesn't work.
So it must be an AppImage/AppImageLauncher issue and not a Wayland vs X11 issue because I use AppImageLauncher on X11 and have the same problem as OP.

My workaround is to download the icon from the repo and change the menu setting/edit the .desktop file to use the downloaded icon instead.

Other apps that I installed with AppImageLauncher works fine (qFlipper, balenaEtcher, Pling Store...) and I didn't have to specify custom icons.

**Comment by flimofly** [comment] 2026-04-01 07:42
This issue persists. I put a .svg version of the OneDrive logo in `/usr/share/icons/hicolor/scalable/apps` and added the file name in the .desktop file as the value of `Icon=`.   When searching for the appimage the icon is properly shown in the app launcher in GNOME and it can be pinned to the dock. 

However, when running it, a new instance of the default gear icon is created next to it. That can be fixed by adding an additional line to the .desktop file:
`StartupWMClass=OneDriveGUI` (if that doesn't work check the value of your appimage WM_Class property by [following this guide](https://itsfoss.com/ubuntu-app-icon-missing/))
